package com.gep;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : FitnessFunction.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//
/**
 * تتس¦¶ب؛¯ت‎ 
 * ¶ش²»ح¬µؤختجâ²ةسأ²»ح¬µؤتتس¦¶ب
 * @author shenzhan
 *
 */
public abstract  class FitnessFunction {
	
	public FitnessFunction(){
		
	}
	
	/**
	 * ¸ِجه±ي´ïہà
	 */
	protected Expression Exp=new Expression();
	/**
	 * ¼ئثمتتس¦¶ب
	 * @param Pop
	 * @param Data
	 * @param Fitness
	 */
	public abstract void GetFitness(Population Pop, double[][] Data,double[] Fitness);
}
