package com.gep;

import java.util.LinkedList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : Chromosome.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//

/**
 * ب¾ة«جهChromosome
 * 
**/
public class Individual implements Cloneable{
	/**
	 * »ùزٍµؤتتس¦ضµ
	**/
	public double Fitness;
	
	public double Value;
	/**
	 * ب¾ة«جه ×ض·û´®
	**/
	public List<String> Chrom;
	
	
	
	public Individual(){
		this.Chrom=new LinkedList<String>();
	
	}
	
	/**
	 * جي¼س»ùزٍ
	 * @param Gene
	 */
	public void AddGene(String[] Gene){
		List<String> listTemp=new LinkedList<String>();
		for(int i=0;i<Gene.length;++i){
			listTemp.add(Gene[i]);
		}
		this.Chrom.addAll(listTemp);
	}
	

	
	/**
	 * Get
	 * @param nIndex
	 * @return
	 */
	public String Get(int nIndex){
		return Chrom.get(nIndex);
	}
	/**
	 * Set
	 * @param nIndex
	 * @param str
	 */
	public void Set(int nIndex, String str){
		Chrom.set(nIndex, str)	;	
	}
	
	/**
	 * ةèضأ¸ِجهµؤضµ
	 * @param Indiv
	 */
	public void SetValue(Individual Indiv) {
		this.Chrom=new LinkedList<String>();
	     for(int i=0;i<Indiv.Chrom.size();++i){
	    	   this.Chrom.add(Indiv.Chrom.get(i));
	     }
	}
	
	/**
	 * ¸ِجه؟ثآ،
	 */
	public Object clone(){
		Individual  Indiv = null;
        try{
           Indiv = (Individual)super.clone();
        }catch(CloneNotSupportedException e){
            e.printStackTrace();
        }
        
        Indiv.Chrom=new LinkedList<String>();
        for(int i=0;i<this.Chrom.size();++i){
            String sCode=new String(this.Chrom.get(i));
            Indiv.Chrom.add(sCode);
        }
        
        Indiv.Fitness=this.Fitness;
        Indiv.Value=this.Value;
        
        return Indiv;
    }

	/**
	 * »ٌب،»ùزٍ  »ùزٍ±à؛إ´س0؟ھت¼
	 * @param n
	 * @return
	 */
	public List<String> GetGene(int n){
		if(n<0 || n>=GepProcess.GeneCount){
			return null;
		}
		
		return this.Chrom.subList(n*GepProcess.GeneLength, n*GepProcess.GeneLength+GepProcess.GeneLength);
		
	}
	
	
}
