package com.gep;

import java.util.LinkedList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : Population.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//

public class Population {
	public int Size; // ضضب؛´َذ،
	public double Fitness; // ضضب؛µؤتتس¦ضµ
	public List<Individual> PopulationSet; // ضضب؛µؤ¼¯؛دجه

	/**
	 * ³ُت¼»¯ضضب؛
	 */
	public Population() {
	     PopulationSet=new LinkedList<Individual>();
	}
	
	/**
	 * جي¼س¸ِجه
	 */
	public void AddIndivdual(Individual Indiv){
		   PopulationSet.add(Indiv);
		   this.Size=PopulationSet.size();
	}
	
	public int GetSize(){
		   return PopulationSet.size();
	}
	
	/**
	 * »ٌب،ؤ³¸ِ¸ِجه
	 */
	public Individual Get(int  nIndex){
		return PopulationSet.get(nIndex);
	}
		
	/** 
	 * ةèضأ¸ِجه
	 */
	public void Set(int nIndex, Individual Indiv){
		  PopulationSet.set(nIndex, Indiv);
	}
}
